# Generated by Django 5.2.5 on 2025-08-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('input', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
