# Generated by Django 4.2.7 on 2025-08-23 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location_hash', models.CharField(max_length=128)),
                ('price_cents', models.IntegerField(default=0)),
                ('scope_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('done', 'Done')], default='draft', max_length=20)),
                ('before_photos', models.JSONField(default=list)),
                ('after_photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_jobs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
